### ISSUE TITLE
Random fails during tests with `httpbin.org`

### ISSUE THREAD

**Issue by AlexV525** [cfug/diox#48]
### Request Statement

- https://github.com/cfug/diox/actions/runs/3764452680/jobs/6398951334
- https://github.com/cfug/diox/actions/runs/3764452680/jobs/6401883595
- https://github.com/cfug/diox/actions/runs/3766331245/jobs/6402719770
- https://github.com/cfug/diox/actions/runs/3766331245/jobs/6402719903
- https://github.com/cfug/diox/actions/runs/3766331245/jobs/6402719977

`https://httpbin.org/` seems can easily fail during tests with GitHub actions, it's likely caused by too many requests at the same time, or the service is unstable, which brings two options to try to prevent failures:
- Avoid too frequent requests.
- Write a mock adapter/transformer/interceptor to test.

**Comment by kuhnroyal** [comment]
There is https://github.com/lomsa-dev/http-mock-adapter which I use in OpenAPI tests.

**Comment by kuhnroyal** [comment]
There is also the possibility of running `httpbin` locally in the pipeline: `docker run -p 80:80 kennethreitz/httpbin`

**Comment by kuhnroyal** [comment]
Something like this could work:

```yaml
jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    services:
      httpbin.org:
        image: kennethreitz/httpbin
        ports:
          - 80:80
```

Not sure if we need a host mapping or if the service name works.
